### ISSUE TITLE
Journeys not being called

### ISSUE THREAD

**Issue by picolloo** [elastic/synthetics#332]
Hi there, 

I'm implementing synthetics using the heartbeat Docker image but my journey is not being called by the elastic module. 
All my files are being placed in `/usr/share/heartbeat/suites`, with name `xxxx.journey.js` but they are not executed. 

My manifest file look like this:
```yml
heartbeat.monitors:
- type: browser
  name: Accounts
  id: accounts-auth
  schedule: "@every 1m"
  source:
    local:
      path: "${SUITES_DIR}"
```

docker-compose.yml:
```yml
version: '3.2'

services:
  heartbeat:
    build:
      context: .
    command: --strict.perms=false -c /etc/heartbeat.yml -e
    env_file:
     - .env
    volumes:
      - type: bind
        source: ./manifests/development/heartbeat.yml
        target: /etc/heartbeat.yml
      - "./dist:/usr/share/heartbeat/suites"
    networks:
      - docker-elk_elk

networks:
  docker-elk_elk:
    external: true

```

I'm unable to deploy my synthetics tests because of it. Am I doing anything wrong?
