### ISSUE TITLE
Run tests separately by using a custom command

### ISSUE THREAD

**Issue by picolloo** [elastic/synthetics#384]
Hi there,

I'm implementing synthetics tests here at my company and trying this tool. 
I currently have about 10 tests grouped by context and they are all started by the default elastic-synthetics command.

What I'm looking for is a way of running they separately, possible by specifying the path in the command. But I haven't found any way of passing flags to the `docker.elastic.co/beats/heartbeat:7.13.0` image default command.

Can you guys help me with this issue?
FYI I'm currently running all tests in the same pod since every file that has the `.journey` prefix is executed.

If you need any extra information or files I'd be glad to share with you.

**Comment by vigneshshanmugam** [comment]
@picolloo You can filter journeys based on tags and match. Find the docs here - https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-browser-options.html#monitor-browser-filter-journeys

These would allow you to group journeys, Let us know if you need any help.

**Comment by picolloo** [comment]
I think I'm having a problem setting up Heartbeat with synthetics. When I run my application I get this command as the startup command inside a Docker container: `/tmp/elastic-synthetics-865777173/node_modules/.bin/elastic-synthetics . --screenshots --json --network --outfd 3`
How can I override this default command?

My Dockerfile looks like this:
```dockerfile
FROM docker.elastic.co/beats/heartbeat:7.13.0

ENV ELASTIC_SYNTHETICS_OFFLINE=true

USER heartbeat

WORKDIR $SUITES_DIR

COPY package.json .
RUN npm i

COPY . .
```

This is my docker-compose.yml
```yml
version: '3.2'

services:
  heartbeat:
    build:
      context: .
    command: -c /etc/heartbeat.yml -e
    env_file:
     - .env
    volumes:
      - type: bind
        source: ./manifests/development/heartbeat.yml
        target: /etc/heartbeat.yml
    networks:
      - docker-elk_elk

networks:
  docker-elk_elk:
    external: true
```

And this is my heartbeat.yml
```yml
heartbeat.monitors:
- type: browser
  name: Accounts
  id: accounts-auth
  schedule: "@every 3m"
  source:
    local:
      path: "${SUITES_DIR}"

fields:
  env: development

tags:
  - development

processors:
  - add_cloud_metadata:

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
  protocol: ${ELASTICSEARCH_PROTOCOL:https}
  ssl.verification_mode: none
```

**Comment by picolloo** [comment]
I tried using this configuration but it appears no being passed to the default command:
`heartbeat_1  | 2021-09-27T14:22:23.019Z INFO    synthexec/synthexec.go:128      Running command: /tmp/elastic-synthetics-463793093/node_modules/.bin/elastic-synthetics . --screenshots --json --network --outfd 3 
in directory: '/tmp/elastic-synthetics-463793093'`

I also keep receiving this warning: `synthexec/synthexec.go:207      error parsing line: invalid character 'a' looking for beginning of value for line: at 22432 ms Runner: end step`.

My heartbeat.yml:
```yml
heartbeat.monitors:
- type: browser
  name: accounts
  id: accounts-auth
  schedule: "@every 1m"
  filter_journeys:
    match: "Sign in*"
  source:
    local:
      path: "${SUITES_DIR}"
```
The journey:
```javascript
journey('Sign in', options => {
  const { page } = options
  const signInPage = new SignInPage(page)

  step('sign in', async () => {
    await signInPage.navigate()
    return signInPage.signIn()
  })

  step('select product', async () => signInPage.selectMarketingProduct())
})
```
