### ISSUE TITLE
Store API credentials in `.config`

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#603]
We currently don't store API keys anywhere in project directories due to the risk of them being pushed. That said, it's very inconveneient to constantly retype them, or have to set an environment variable.

Most other CLI tools, like `gh` use the `~/.config` directory for such purposes, for example:

```
# ~/.config/gh/hosts.yml

github.com:
    oauth_token: SEKRET
    user: andrewvc
    git_protocol: ssh
```

We should do similar, I think something like:

```
# ~/.config/elastic_synthetics/hosts.yml

"my-kibana-url":
    api_key: API_KEY
```

would work
