### ISSUE TITLE
Improve lightweight project monitor validation

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics#624]
Today, it's possible to create an http monitor via Synthetics `push` with config like:

```yaml
heartbeat.monitors:
- type: http
  schedule: @every 5s
  name: lightweight
  id: lightweight-project
```

Noticeably, this config is missing a `url` key, so this monitor will never log any data.

Presently, when Synthetics validates an object to push, it only looks for required fields. As `url` is specific to the http monitor type, it isn't required and thus passes the validation. As part of the process of submitting project monitor config, we add supplemental fields. `url` is one of those fields, and a default value of `''` is supplied. By modifying the behavior to avoid adding default fields, we can trigger a failure in the Kibana-side validation.

We should also investigate the other lightweight monitor types for similar areas where this problem exists for non-required fields.
