### ISSUE TITLE
[CLI] Provide ability to independently set `data_stream.namespace` from `--space`

### ISSUE THREAD

**Issue by BenB196** [elastic/synthetics#749]
Today, when you use the CLI and set the `--space` value, it will set the value for `data_stream.namespace` as well. You should be allowed to independently set the value of `data_stream.namespace`.

If you attempt something like:

```yaml
heartbeat.monitors:
  - type: icmp
    data_stream:
      namespace: "public.default.development"
    name: google.com
    id: google.com
    enabled: true
    hosts:
      - "google.com."
    schedule: "@every 20s"
```

And run the command

```bash
npx @elastic/synthetics push --yes --id icmp-development --space observability --private-locations 'S0000 - Development'
```

You get the error:

```
✖ Error
   > Unsupported Heartbeat option: monitor(tstrtr01.heroes.bayada.com)
       The following Heartbeat options are not supported for icmp project monitors in 8.6.2: data_stream.namespace. You monitor was not created or updated.
```

---

# Use Case

If you want to have a number of different monitors in the same space, but want to have different retention times on them, you need to use something like `data_stream.namespace` to differentiate the data.

**Comment by shahzad31** [comment]
specifying at root level already works 

```
heartbeat.monitors:
  - type: http
    name: Todos Lightweight Test 0
    id: todos-lightweight-test-0
    enabled: true
    urls: 'https://elastic.github.io/synthetics-demo'
    schedule: '@every 60m'
    timeout: 18s
    namespace: food
```
