### ISSUE TITLE
Ability to set custom processors

### ISSUE THREAD

**Issue by BenB196** [elastic/synthetics#750]
If you try to set custom processors today, you will get an error saying they're unsupported.

```yaml
heartbeat.monitors:
  - type: icmp
    name: google.com
    id: google.com
    enabled: true
    hosts:
      - "google.com."
    schedule: "@every 20s"
    processors:
      - add_fields:
          target: host
          fields:
            type: "test"
```

And run the command

```bash
npx @elastic/synthetics push
```

You will get the error message:

```
✖ Error
   > Unsupported Heartbeat option: monitor(tstrtr01.heroes.bayada.com)
       The following Heartbeat options are not supported for icmp project monitors in 8.6.2: processors. You monitor was not created or updated.
```

---

# Use Case

Today, the Synthetics app is very limited in functionality, and extremely limited in the ability to set metadata on monitors. Without the ability to set custom metadata on monitors, the usability of this feature is extremely limited, and often requires reverting back to legacy implementation. Processes allow for the ability to set this metadata as the user desires.

(Note: I've considered using Elasticsearch ingest pipelines to add this metadata, however it is not a scalable solution when you have several thousand monitors running several times a minute)
