### ISSUE TITLE
Validate params for id field

### ISSUE THREAD

**Issue by shahzad31** [elastic/synthetics#793]
Currently user can configure monitor certain monitor configurations with params that cause problems.

For instance, it's allow params in id field. We should validate this and don't allow params in certain fields. Since this will have an issue with how results are displayed against a monitor in UI 

For example, for a lightweight monitor:

```
heartbeat.monitors:
- type: http
  name: Manager Login ${environment}
  id: "manager-login-${environment}" <--- this should not be allowed 
  enabled: true
  urls: "https://${baseUrl}/manager/"
  schedule: '@every 5m'
  timeout: 16s
  alert.status.enabled: false
```

ACs:
- Stop expanding variables in:
  - name
  - id
  - schedule
  - tags
- Escape all escape chars in those fields so heartbeat does not interpolate them
- Document that users should use local environment variables to parameterize things at push time, not runtime
  - Provide example of pushing to multiple environments
