### ISSUE TITLE
[Bug] Updating lightweight monitor in project generates error

### ISSUE THREAD

**Issue by renzedj** [elastic/synthetics#843]
# Issue

Attempting to update a lightweight monitor in a project generates the following error:

```
> security_exception
 Root causes:
   security_exception: action [indices:data/read/search] is unauthorized for API key id [<key-id>] of user [<my-user-id>], this action is granted by the index privileges [read,all]
     Failed to update journey: 7f5243e1-b593-4639-ba42-f081c802c79d
```

> **Note:** The user ID shows my personal ID (as expected), however I am the Elastic Cloud admin for our organization.

# Steps to Replicate Error

1. Create the following lightweight test in an `@elastic/synthetics` project:
```yaml
heartbeat.monitors:
  - id: '7f5243e1-b593-4639-ba42-f081c802c79d'
    name: 'Google'
    type: 'http'
    enabled: true
    alert.status.enabled: true
    check.request.method: 'GET'
    response:
      include_body: 'on_error'
      include_headers: true
    urls: 'https://google.com/'
    schedule: '@every 5m'
    timeout: '15s'
```
2. Push to Kibana: `SYNTHETICS_API_KEY=<api_key> npm run push`
3. Change `alert.status.enabled: false` 
4. Push to Kibana: `SYNTHETICS_API_KEY=<api_key> npm run push`

> **Notes:**
> * I have generated a new API key in the current version of Kibana (8.10.x) to validate that this isn't an issue that's already been resolved in Kibana.
> * Workaround is to update the ID, which deletes the old monitor and creates the new, but this doesn't preserve monitor history.

# Versions

* Elastic Cloud: 8.10.0, 8.10.2
* `@elastic/synthetics`: 1.4.0
