### ISSUE TITLE
yaml anchor support for lightweight monitors

### ISSUE THREAD

**Issue by willemsendennis** [elastic/synthetics#888]
We have a large list of similar http lightweight monitors, that need e.g. the same checks. To be DRY it would be nice if yaml anchors would be supported to be able to do something like this:

```yaml
defaults: &defaults
  type: http
  schedule: '@every 5m'
  timeout: 60s
  private_locations:
    - some-location-dev
    - some-location-staging
  check.response:
    json:
      - description: is active
        expression: 'status == "active"'
      - description: is CapabilityStatement
        expression: 'resourceType == "CapabilityStatement"'

heartbeat.monitors:
- name: Monitors are awesome
  id: awesomemonitor1
  urls: "https://some-unique-url/endpoint1"
  << : *defaults
- name: Another awesome monitors
  id: awesomemonitor2
  urls: "https://some-other-unique-url/and-different-endpoint"
  << : *defaults

```
